# Generated by Django 4.1.3 on 2022-12-08 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0009_studio_location_order'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='studios.studio'),
        ),
    ]
