# Generated by Django 4.1.3 on 2022-12-09 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_rename_duration_classtype_default_compacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtype',
            old_name='default_compacity',
            new_name='default_capacity',
        ),
    ]
