# Generated by Django 4.1.3 on 2022-11-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gym_plan", "0003_remove_card_owner_card_name"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaluser",
            name="card",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to="gym_plan.card",
            ),
        ),
    ]
