# Generated by Django 4.1.3 on 2022-11-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gym_plan", "0005_remove_card_name_alter_card_cvv_alter_card_number"),
        ("accounts", "0003_generaluser_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generaluser",
            name="card",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_by",
                to="gym_plan.card",
            ),
        ),
    ]
