# Generated by Django 4.1.3 on 2022-11-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_generaluser_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaluser",
            name="paid_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
