# Generated by Django 4.1.3 on 2022-12-08 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_plan', '0007_alter_card_cvv'),
        ('accounts', '0006_generaluser_paid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='using_by', to='gym_plan.card'),
        ),
        migrations.AlterField(
            model_name='generaluser',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='gym_plan.gymplan'),
        ),
    ]
