# Generated by Django 4.1.3 on 2022-11-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_studio_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='geographical_location',
            field=models.FloatField(),
        ),
    ]
