# Generated by Django 4.1.3 on 2022-11-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_alter_studio_geographical_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='geographical_location',
        ),
        migrations.AddField(
            model_name='studio',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
