# Generated by Django 4.1.3 on 2022-11-15 23:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_alter_studio_latitude_alter_studio_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='directions',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('studio_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studio')),
            ],
        ),
    ]
