# Generated by Django 4.1.3 on 2022-11-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0007_remove_studio_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='directions',
        ),
    ]
