# Generated by Django 4.1.3 on 2022-11-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0008_remove_studio_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='location_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
