# Generated by Django 4.1.3 on 2022-11-12 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("gym_plan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CREDIT", "credit"), ("DEBIT", "debit")],
                        max_length=50,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card",
                        to="accounts.generaluser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gymplan",
            name="period",
            field=models.CharField(
                choices=[
                    ("DAY", "day"),
                    ("MONTH", "month"),
                    ("SEASON", "season"),
                    ("ANNUL", "annul"),
                ],
                default="DAY",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to="gym_plan.card",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to="accounts.generaluser",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to="gym_plan.gymplan",
                    ),
                ),
            ],
        ),
    ]
