# Generated by Django 4.1.3 on 2022-11-16 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_plan", "0005_remove_card_name_alter_card_cvv_alter_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="time",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
