# Generated by Django 4.1.3 on 2022-11-19 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_plan', '0006_alter_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='CVV',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
